name: Test Automation WorkFlow

on:
  schedule:
    - cron: 00 18 * * * 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
          path: ~/.m2
          key: ${{ runner.os }}-maven{{ hashFiles('**/pom.xml') }}
          
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLamdaTest=true -DisHeadless=false

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Logs
        path: logs/

    - name: Upload Screenshots folder
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: screenshots
          path: screenshots/

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy to GitHub Pages
      if: always()
      uses: JamersIves/github-pages-deploy-action@v4.8.0
      with:
         folder: public/extent-reports/
         token: ${{ secrets.PATREPORTS }}
         clean: true
       
        
